spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:file:.env.local[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasteam}
    username: ${DB_USERNAME:tasteam}
    password: ${DB_PASSWORD:tasteam}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true

  flyway:
    enabled: false
    url: ${FLYWAY_URL:${DB_URL:jdbc:postgresql://localhost:5432/tasteam}}
    user: ${FLYWAY_USER:${DB_USERNAME:tasteam}}
    password: ${FLYWAY_PASSWORD:${DB_PASSWORD:tasteam}}
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  sql:
    init:
      mode: always

  security:
    jwt:
      accessTokenExpiration: 600000   # 10분
      refreshTokenExpiration: 1800000 # 30분

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: debug
    org.springframework.security: DEBUG
    org.springdoc: ERROR

naver:
  maps:
    base-url: https://maps.apigw.ntruss.com
    api-key-id: ${NAVER_MAPS_API_KEY_ID:dummy}
    api-key: ${NAVER_MAPS_API_KEY:dummy}

tasteam:
  webhook:
    enabled: false
