spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:file:../.env.local[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/tasteam
    username: tasteam
    password: tasteam

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    jwt:
      accessTokenExpiration: 60000    # 1분
      refreshTokenExpiration: 180000  # 3분

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: debug

naver:
  maps:
    base-url: https://naveropenapi.apigw.ntruss.com
    api-key-id: ${NAVER_MAPS_API_KEY_ID:dummy}
    api-key: ${NAVER_MAPS_API_KEY:dummy}
